### ISSUE TITLE
Account linking.

### ISSUE THREAD

**Issue by saul-avikar** [robrotheram/taiga-contrib-openid-auth#18]
Is there a method for linking existing accounts to the OpenID authentication system or does it have to be created through the OpenID process as a public registrant?

**Comment by robrotheram** [comment]
I have not tested this scenario and I not that familiar as to how it will handle it. From looking at the database there is the user table which stores the user and a auth table that links a user to an external auth token and user ID

I think it should be possible to link to an existing user but I think you will need to make sure that username matches. In the latest version of the plugin I made this configurable so you can map any field returned from the openid provided as the username field taiga will uses

**Comment by saul-avikar** [comment]
@robrotheram Thanks for that, I have just tested account linking and it just simply works if the email matches - the username and name does not seem to matter.
