### ISSUE TITLE
Our Oompa Loompas have not been able to get your credentials from OpenID.

### ISSUE THREAD

**Issue by YZ2999** [robrotheram/taiga-contrib-openid-auth#22]
Hi, 
I am trying to get taiga talking to keycloak. The keycloak longin went through but when it redirects to taiga I received the following msg:
_Oops, something went wrong...  Our Oompa Loompas have not been able to get your credentials from OpenID._
I could not work out what happend  while I noticed in the keycloak log the redirectAccessCode state is null. Any recommendations will be appreciated. Thanks. 
**keycloak log:**
_07:31:31,082 DEBUG [org.keycloak.protocol.oidc.OIDCLoginProtocol] (default task-25) **redirectAccessCode: state: null**
07:31:31,083 DEBUG [org.keycloak.events] (default task-25) type=LOGIN, realmId=XXX, clientId=taiga, userId=XXX, ipAddress=172.23.0.1, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://localhost:9000/login, consent=no_consent_required, code_id=XXX, response_mode=query, username=XXX, authSessionParentId=xxx, authSessionTabId=xxx_

**Comment by robrotheram** [comment]
Hi, Not sure what is happening there sorry,
Things to check. in the browser open up the network tools tab and there is a setting called "perverse/persist log" and you should see the full url it is sending the SSO provider.
```
https://auth.***********.***/auth/realms/***********/protocol/openid-connect/auth?redirect_uri=https://taiga.***********.***/login&client_id=******&response_type=code
```
Other then that I am not sure. I would check what the scope is configured.

**Comment by YZ2999** [comment]
Hi Robert, your suggestion did help. from the log I identified that the issue was caused by 
PUBLIC_REGISTER_ENABLED: "false". After I changed it to true, it worked.  Many thanks. 

YZ
