### ISSUE TITLE
Support for Taiga v.5

### ISSUE THREAD

**Issue by niwo** [robrotheram/taiga-contrib-openid-auth#4]
Hi,

Is this project still active and are there are there any plans to support Taiga v.5 ?

Thanks!

**Comment by robrotheram** [comment]
Sorry for the late reply. I have tested it on 5.0.7 still works fine. I'll update the Readme.
The project runs on my limited free time, I am fairly active when it comes to PR's from other users.

**Comment by niwo** [comment]
Very cool, thanks!
